### ISSUE TITLE
could you please share the data online

### ISSUE THREAD

**Issue by Brucechen13** [foamliu/Image-Captioning#1]
Hi,thanks for sharing your codes and it's very helpful for me. However I can't download the data from the website because it requires for id vertify. Could you upload your data to other website so that it can be download easier?

**Comment by RamatovInomjon** [comment]
Hi @Brucechen13 , did you find dataset for training? the link is invalid now, couldn't open. Please can you share your data, in other website or cloud ?

**Comment by RamatovInomjon** [comment]
Hi @foamliu , thanks for great job, please can you guide ?
How should be data format for training? is there any labeling tool for data preparation,
